dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"
install:
    - pip install pipenv
    - pipenv install 
    - pipenv install coveralls
script:
    - pipenv run coverage run tests/test_fpsm.py
after_success:
    - pipenv run coveralls
